..EEFF..FFEEEF.
Failed tests:
-------------
1) TestAnotherThing.test2_Err1
test/test_with_err_fail_pass.LUA:41: attempt to perform arithmetic on a table value
stack traceback:
	[C]: in function 'xpcall'

2) TestAnotherThing.test2_Err2
test/test_with_err_fail_pass.LUA:45: attempt to perform arithmetic on a table value
stack traceback:
	[C]: in function 'xpcall'

3) TestAnotherThing.test3_Fail1
test/test_with_err_fail_pass.LUA:49: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.LUA:49: in function 'TestAnotherThing.test3_Fail1'

4) TestAnotherThing.test3_Fail2
test/test_with_err_fail_pass.LUA:53: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.LUA:53: in function 'TestAnotherThing.test3_Fail2'

5) TestSomething.test2_Fail1
test/test_with_err_fail_pass.LUA:15: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.LUA:15: in function 'TestSomething.test2_Fail1'

6) TestSomething.test2_Fail2
test/test_with_err_fail_pass.LUA:19: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.LUA:19: in function 'TestSomething.test2_Fail2'

7) TestSomething.test3_Err1
test/test_with_err_fail_pass.LUA:23: attempt to perform arithmetic on a table value
stack traceback:
	[C]: in function 'xpcall'

8) TestSomething.test3_Err2
test/test_with_err_fail_pass.LUA:27: attempt to perform arithmetic on a table value
stack traceback:
	[C]: in function 'xpcall'

9) testFuncErr1
test/test_with_err_fail_pass.LUA:66: attempt to perform arithmetic on a table value
stack traceback:
	[C]: in function 'xpcall'

10) testFuncFail1
test/test_with_err_fail_pass.LUA:62: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.LUA:62: in function 'testFuncFail1'

Ran 15 tests in 0.002 seconds, 5 successes, 5 failures, 5 errors
