..FF..FFF.
Failed tests:
-------------
1) TestAnotherThing.test3_Fail1
test/test_with_err_fail_pass.LUA:49: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.LUA:49: in function 'TestAnotherThing.test3_Fail1'

2) TestAnotherThing.test3_Fail2
test/test_with_err_fail_pass.LUA:53: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.LUA:53: in function 'TestAnotherThing.test3_Fail2'

3) TestSomething.test2_Fail1
test/test_with_err_fail_pass.LUA:15: expected: 0, actual: 2
stack traceback:
	test/test_with_err_fail_pass.LUA:15: in function 'TestSomething.test2_Fail1'

4) TestSomething.test2_Fail2
test/test_with_err_fail_pass.LUA:19: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.LUA:19: in function 'TestSomething.test2_Fail2'

5) testFuncFail1
test/test_with_err_fail_pass.LUA:62: expected: 0, actual: 3
stack traceback:
	test/test_with_err_fail_pass.LUA:62: in function 'testFuncFail1'

Ran 10 tests in 0.001 seconds, 5 successes, 5 failures, 5 non-selected
